### ISSUE TITLE
TryAPL/TIO selection doesn't load from permalink

### ISSUE THREAD

**Issue by AviFS** [razetime/APLgolf#1]
It shows up as TryAPL when loading a link, even when TIO is selected and being run.

Try here: https://razetime.github.io/APLgolf/?h=AwA&c=e9Q17VFv56O2ieoV6kDyUe@KQysOrTfUfdQ3FQA&f=AwA&i=S@MyVDAAQkMFIwUTIDYAAA&r=tio&l=apl-dyalog&m=tradfn&n=f#

Running that will work. But if you click on "options" it shows TryAPL, even though TIO is really selected and running.

To test this, select TIO and then select TryAPL again. It won't run the same way once it's reselected; it was TIO running.

(There's also presumably some variable set to TIO somewhere, which you can check instead, of course!)

**Comment by razetime** [comment]
Should be fixed in https://github.com/razetime/APLgolf/commit/f0eb8c0e35480efae3239ed717d8f733b3dbc234.
