### ISSUE TITLE
Runner name changed; old links not working

### ISSUE THREAD

**Issue by AviFS** [razetime/APLgolf#2]
[This link used to work, but doesn't anymore.](https://razetime.github.io/APLgolf/?h=e9Q31dP/UdsEAwA&c=e9S1SNvo8PRHvd2Peroe9S4FMXonAQA&f=S1MwUDAEQgMFA640BBtMAtlgMQOorCFc3AAA&i=AwA&r=tryAPL&l=apl-dyalog&m=train&n=f#)

As a result, that link has no syntax highlighting and the top-right buttons don't work. 

[@cairdcoinheringaahing](https://github.com/cairdcoinheringaahing) confirmed the bug and [@dzaima ](https://github.com/dzaima) figured out the cause!

In [this commit](https://github.com/razetime/APLgolf/commit/74469e811e95cb1b847b18834bf4445f2bb7ce4e), the runner name was changed from 'tryAPL' to 'tryapl' so all links using that runner generated before the name change no longer work.

**Fix:** For back-compatibility, recognize both names in links. Either of 'tryAPL' or 'tryapl' should be recognized in a link, even if the first is deprecated.

**Comment by razetime** [comment]
merged Avi's fix.
