### ISSUE TITLE
Preserve options on reload

### ISSUE THREAD

**Issue by sloorush** [razetime/APLgolf#6]
I am not sure how you are storing the options, but preserving those options in the browser memory(local storage or cookies) can be an easy quality-of-life enhancement that would benefit the users.

**Comment by razetime** [comment]
the options are stored in the URL, which is a permalink that restores the options. Adding local storage would mess with any other permalinks, and since this is static, I cannot track tab sessions for restoring data. If you have any ideas how to do this without hurting existing generated URLs, I am all ears.

**Comment by sloorush** [comment]
@razetime, Ah okay, I guess for sharing the golf URL you "need" to keep those permalinks. Is that correct?

**Comment by sloorush** [comment]
Shooting from the hip, can you store stuff like options in the permalinks so people can just bookmark them and it opens the same options they set the last time they updated the bookmarks?

**Comment by razetime** [comment]
i had an idea earlier today: if there are no URL parameters given, then APLgolf will restore the previous session. Does that sound okay?

**Comment by sloorush** [comment]
Yep, that sounds reasonable to me!

**Comment by razetime** [comment]
i've changed the source to preserve options on a non-permalink. do tell me if it breaks, the code is held together with duct tape.

**Comment by sloorush** [comment]
When I try it with tryAPL it just goes to running mode and does not return a result.

Is this happening to you as well?

**Comment by razetime** [comment]
pleas explain the steps you performed *exactly*.

**Comment by sloorush** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/54478821/219260076-d16e9bf9-586f-4a95-bcbc-c3b5b9e6f2e7.png">

It just gets stuck on running (is there something on doing incorrectly?)

**Comment by sloorush** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/54478821/219260412-834cc611-2c08-4ab6-802a-adaafb288c57.png">

this works...

but anything with tryAPL gets stuck on "running"

**Comment by razetime** [comment]
i am not able to recreate this problem. try sending a permalink.

**Comment by sloorush** [comment]
# [APL(Dyalog Unicode)][1], <sup><s></s></sup>4 bytes <sup>[SBCS][2]</sup>
```
{⍵}5
```
[Try it on APLgolf!](https://razetime.github.io/APLgolf/?h=AwA&c=q37Uu7XWFAA&f=AwA&i=MwUA&r=tryapl&l=apl-dyalog&m=tradfn&n=f)

[1]: https://dyalog.com
[2]: https://github.com/abrudz/SBCS

A full program which ____.

**Comment by sloorush** [comment]
These might be helpful to debug

Console logs:
![image](https://user-images.githubusercontent.com/54478821/219261103-3b9417c6-69dd-49f6-b2aa-3ecefdd03942.png)

Network tab:
![image](https://user-images.githubusercontent.com/54478821/219261156-dd0ef0fa-6855-4972-9130-3253bc9bf090.png)

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/54478821/219261270-d7a1ad08-70ec-4932-9ecf-8022d77c1d5b.png">

**Comment by razetime** [comment]
the permalink runs correctly. it may have been some problem with the tryapl side. just try a hard refresh with ctrl+F5.

**Comment by sloorush** [comment]
oh, still doesn't work for me (not even with incognito). I'll check it out in the evening maybe, something to do with network cache. I'll let you know

Edit: maybe this is something with safari?

**Comment by razetime** [comment]
it might be? I will ask on the apl farm.

**Comment by razetime** [comment]
So, this is apparently a CORS issue on safari (not sure if it's *only* Safari) that pops up after  ~30 seconds. This is not related to localStorage so please make a new issue.
